spring.application.name=wotTankRating

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/tankRanking
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
# Change to "create" to create the database scheme
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=5000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect